const OUTER_CHART_RADIUS = 120;
const SCALE_PARAM = 1.1;
const INNER_CHART_RADIUS = 70;
const CHART_SIZE = OUTER_CHART_RADIUS * SCALE_PARAM * 2;
const TEXT_SIZE = 60;

export {
	OUTER_CHART_RADIUS,
	CHART_SIZE,
	INNER_CHART_RADIUS,
	SCALE_PARAM,
	TEXT_SIZE
};
